INSERT INTO product (product_name, poster_path, description, price, quantity)
VALUES
    ('La basique', 'https://gifdb.com/images/high/fortnite-dances-216-x-206-gif-n8eo9q2brnktm3d6.gif', "La basique, c'est la simplicité à son apogée. Ronde, chaleureuse, elle séduit à chaque bouchée. Familiale et rassurante, son goût inimitable en fait un choix sûr, celui qui satisfait toujours, sans jamais décevoir, à chaque instant.", 500, 15),
    ('La funky', 'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXBjNHQ4eTNxbjdhbjFkb290bWlqbjFucHdyM3JydXA2M25kMWM4OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1APhATvqD65r966yCP/giphy.gif', "La funky, c’est l’esprit d’aventure en chaque bouchée. Elle bouscule les codes, étonne à chaque croque, et enflamme les papilles. Sans crainte d’originalité, elle se distingue, offrant un tourbillon de saveurs qui fait vibrer les sens à chaque instant.", 600, 20),
    ("L'entraînante" , 'https://i.gifer.com/fy2C.gif', "L’entraînante, c’est l’optimisme incarné. Dès la première bouchée, elle t’emporte dans un tourbillon de saveurs. Sa vivacité et sa joie de vivre sont contagieuses, t’invitant à savourer l’instant. Une explosion de plaisir qui te pousse à revenir sans fin.", 1100, 12),
    ('La joviale', 'https://i.gifer.com/XqyP.gif', "La joviale, c’est une explosion de bonne humeur à chaque instant. Elle rayonne par son caractère pétillant et chaleureux, invitant à la convivialité. Parfaite pour égayer n’importe quel moment, elle transforme chaque part en une célébration du bonheur.", 1600, 8),
    ('Tacos Poulet', 'https://i.gifer.com/Vtj1.gif', "La Tacos Poulet incarne un équilibre parfait entre tendreté et saveurs. Chaque bouchée offre une expérience réconfortante, où le poulet grillé se mêle aux épices et sauces, créant une fusion gourmande à savourer sans modération.", 1500, 18),
    ('La souriante', 'https://i.gifer.com/VJep.gif', "La Souriante évoque une expérience légère et pleine de joie. Son aspect chaleureux et accueillant fait sourire dès le premier regard. Une vraie explosion de saveurs simples mais satisfaisantes, qui apportent une touche de bonheur à chaque instant.", 750, 10),
    ('Coink', 'https://i.gifer.com/XOsX.gif', 'Coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink. Coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink, coink.', 350, 50),
    ('La baleze', 'https://i.gifer.com/7HwL.gif', "La baleze, c'est la star des sensations fortes, un mélange de puissance et de caractère. Elle impose une présence et ne laisse personne indifférent. Un choix pour ceux qui ne veulent pas faire dans la demi-mesure.", 250, 30);